Merge 86-correct-footer-horizontal-margin into develop
StudyCrew/StudyCrew pull request #105
Opened 2023-12-24 13:42 UTC by JacobHeldt

## What

The padding in the footer was adjusted to align with the padding in other sections of the homepage (150px). Additionally, the spacing of items in the footer was adjusted, which results in a slightly altered design on desktop devices. The social media icons were also adjusted to be coherent with our marketing strategy.

## Why

The padding on the footer did not align with the padding of other sections. Furthermore, team members expressed concern about the design of the footer section on desktop devices.

## How

Edited Footer.css; Replaced certain social media icons with other social media icons.

## Related Issues

This pull request is focused on desktop and does not take into account the mobile design. The mobile design will be adjusted with issue #80

## Screenshots / GIFs (if applicable)

<img width="1426" alt="image" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/33200256-1a60-464f-8bb1-e190c995c252">

## Checklist

- [x] I have tested these changes locally
- [x] I have ensured my code follows the project's coding style
- [ ] I have updated the documentation accordingly
- [x] My changes do not introduce any new warnings or errors
- [x] All tests pass successfully
- [ ] I have added/updated unit tests (if necessary)

2023-12-24 18:49 UTC, kylescudder commented
@JacobHeldt could these CSS changes please be done using tailwindcss as this is the CSS framework we are using with the project. 

Can you please also make sure that your changes follow the linting conversions (tabs etc) so it is easier to tell what has actually been changed, and what is just refactoring?

Cheers

2023-12-29 15:12 UTC, kylescudder requested changes
There seems to be a number of linting issues that need resolving, can you please fix these so we can tell what is a real change to a line, and what is a linting change (tabs, line length etc)

2023-12-29 15:12 UTC, kylescudder commented on components/Footer/Footer.tsx
> +		<div className="bg-[#f2f7ff] grid grid-cols-3 lg:grid-cols-5 gap-4 px-6 lg:px-[150px] py-6 items-center">
Can we please use the tailwind configured `bg-zircon-50` for this?
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/6a119fd6-3426-4787-8e76-96fc86208af2)

2024-01-02 21:06 UTC, kylescudder commented
Has something happened to the mobile footer design?

![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/bf42b68b-9255-4e64-a2ac-63c0fb744a93)

2024-01-02 21:06 UTC, kylescudder requested changes

2024-01-02 21:06 UTC, kylescudder commented on components/Footer/Footer.tsx
> +		<div className="bg-zircon-50 grid grid-cols-3 lg:grid-cols-5 gap-4 px-6 lg:px-[150px] py-6 items-center">
This line is 113 characters long, the linting limit is 110, please sort this? I know it sounds picky sorry.

2024-01-02 21:06 UTC, kylescudder commented on components/Footer/Footer.tsx
> +				<img src="/assets/Logo.svg" alt="Logo" className='w-10'/>
Can you please use the `next/image` component for this? It should look like this:

```javascript
import Image from 'next/image'
import Logo from '../../public/assets/Logo.svg'

<Image alt='Logo' src={Logo} className='w-10' />
```

2024-01-03 21:02 UTC, JacobHeldt commented
> Has something happened to the mobile footer design?
> 
> ![image](https://private-user-images.githubusercontent.com/74150974/293788735-bf42b68b-9255-4e64-a2ac-63c0fb744a93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTUwMjIsIm5iZiI6MTcwNDMxNDcyMiwicGF0aCI6Ii83NDE1MDk3NC8yOTM3ODg3MzUtYmY0MmI2OGItOTI1NS00ZTY0LWEyYWMtNjNjMGZiNzQ0YTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDIwNDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NWZhNmZkN2NjZmE5NDA5MzQ1ZTFjMzM5YjIzMmUwNzQwNDQxMzBkZGZkMjNkOGYxMTRhMWNmOGY4OTJjNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RfXce4IN__j538E86z_XYgFOu_URgSPxxLR-Mr8e0Fs)

Issue #80 addresses the spacing issues of the footer on mobile. I could also resolve the mobile problems in this pull request, if that is preferred.

2024-01-06 22:47 UTC, kylescudder approved these changes

2024-01-06 22:49 UTC, merged