Merge 185-linting-resolve-outstanding-linting-issues into develop
StudyCrew/StudyCrew pull request #186
Opened 2024-01-11 12:59 UTC by kylescudder

## What

Resolved multiple linting issue throughout the project

## Why

To keep the code style consistent, this will make it easier in the long run as the project grows.

## How

Ran `pnpm lint` and resolved the issues that it reported.

## Checklist

- [x] I have tested these changes locally
- [x] I have ensured my code follows the project's coding style
- [x] I have updated the documentation accordingly
- [x] My changes do not introduce any new warnings or errors
- [x] All tests pass successfully
- [x] I have added/updated unit tests (if necessary)

2024-01-11 14:01 UTC, f3rno64 requested changes
We need to adjust the linter config to indent with spaces instead of tabs, and add a `format` command to the manifest to use [prettier](https://prettier.io/), along with pre-commit hooks to run the linter and tests prior to a commit being made. This is a separate task, one which I need to open an issue for, but I'm just noting it here.

For now, adjust the linter config to allow all-caps variable names for constants.

2024-01-11 14:40 UTC, f3rno64 commented on components/Features/Features.tsx
> -	FEATURES_STAGES,
Alright let's discuss on discord, I'll approve for now.

2024-01-14 15:15 UTC, kylescudder commented
@f3rno64 if you are happy I am going to close this now as it has been superseded by #193  and #196.

2024-01-14 15:44 UTC, f3rno64 commented
Yep, go ahead.

2024-01-14 17:12 UTC, closed without merging