Issue459 solved
StudyCrew/StudyCrew pull request #555
Opened 2024-09-03 03:29 UTC by career-tokens

![image](https://github.com/user-attachments/assets/59751c38-6924-4e54-ae08-0a5f3fdc2f93)

2024-09-03 16:38 UTC, JacobHeldt requested changes
Thank you for working on this @career-tokens! Can you please make sure the header takes up the full with and is at the top of the page?

2024-09-03 17:19 UTC, career-tokens commented
Tbh for a full screen web app I believe that would look very weird
 now I have allowed the user to apply his/her classname to apply custom style

2024-09-06 16:59 UTC, zaibutcooler commented on src/components/layout/PageHeader.tsx
> +            <path d="M26.0001 24.5H6.00009C5.82506 24.4989 5.65338 24.452 5.5022 24.3638C5.35101 24.2756 5.22563 24.1492 5.13857 23.9974C5.05152 23.8456 5.00584 23.6735 5.0061 23.4985C5.00637 23.3235
have you thought about putting these svgs into separate files, components or even variables, not a good practice.

2024-09-06 17:00 UTC, zaibutcooler commented on tailwind.config.ts
> +        header_background: "#f3f4f8",
don't understand why you need to add more variables into global tailwind.

2024-09-06 17:02 UTC, zaibutcooler requested changes

2024-09-06 17:02 UTC, zaibutcooler commented on src/app/check/page.tsx
> +'use client'
better clean up the check page after testing. if someone's also working in this part, and push, we'll get merge conflict.

2024-09-21 09:13 UTC, JacobHeldt approved these changes

2024-09-21 09:13 UTC, merged